# AUTOGENERATED! DO NOT EDIT! File to edit: ../drive/MyDrive/Colab Notebooks/Copy of gradio_interface.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'intf', 'classify_image']

# %% ../drive/MyDrive/Colab Notebooks/Copy of gradio_interface.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% ../drive/MyDrive/Colab Notebooks/Copy of gradio_interface.ipynb 4
learn = load_learner('export.pkl')

# %% ../drive/MyDrive/Colab Notebooks/Copy of gradio_interface.ipynb 6
categories = learn.dls.vocab

def classify_image(img):
  pred,idx,probs = learn.predict(img)
  return dict(zip(categories, map(float, probs)))

# %% ../drive/MyDrive/Colab Notebooks/Copy of gradio_interface.ipynb 8
intf = gr.Interface(fn=classify_image,inputs=gr.Image(type="pil"),outputs=gr.Label(),examples=['cocker.jpg', 'doberman.jpg', 'germanshep.jpg'])
intf.launch(inline=False)
